# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-added-large-files
  - id: check-shebang-scripts-are-executable
  - id: check-json
  - id: check-yaml
  - id: double-quote-string-fixer
  - id: end-of-file-fixer
  - id: no-commit-to-branch
    args: [--branch, master]
  - id: trailing-whitespace
- repo: local
  hooks:
  - id: clang-format
    entry: hooks/clang_format.sh
    language: script
    name: clang-format
    stages: [commit]
    types: [c++]
  - id: dev-marker
    entry: hooks/dev_marker.sh
    language: script
    name: dev-marker
  - id: isort
    entry: hooks/isort.sh
    language: script
    minimum_pre_commit_version: 2.9.0
    name: isort
    types_or: [python, pyi]
  - id: mypy
    entry: hooks/mypy.sh
    language: script
    minimum_pre_commit_version: 2.9.0
    name: mypy
    types_or: [python, pyi]
  - id: pylint
    entry: hooks/pylint.sh
    language: script
    minimum_pre_commit_version: 2.9.0
    name: pylint
    types_or: [python, pyi]
  - id: symbolic-links
    entry: hooks/symbolic_links.sh
    language: script
    name: symbolic-links
    stages: [commit]
    types: [symlink]
  - id: xenon
    entry: hooks/xenon.sh
    language: script
    minimum_pre_commit_version: 2.9.0
    name: xenon
    types_or: [python, pyi]
  - id: yapf
    entry: hooks/yapf.sh
    language: script
    minimum_pre_commit_version: 2.9.0
    name: yapf
    types_or: [python, pyi]
