- id: clang-format
  description: Execute clang-format check.
  entry: hooks/clang_format.sh
  language: script
  name: clang-format
  stages: [commit]
  types: [c++]
- id: cpp-check
  description: Execute cpp-check check.
  entry: hooks/cpp_check.sh
  language: script
  name: cpp-check
  stages: [commit]
  types: [c++]
- id: dev-marker
  description: Prevent committing DEV MARKERs
  entry: hooks/dev_marker.sh
  language: script
  name: dev-marker
  stages: [commit]
- id: isort
  description: Sort Python imports
  entry: hooks/isort
  language: script
  minimum_pre_commit_version: 2.9.0
  name: isort
  types_or: [python, pyi]
- id: mypy
  description: Run mypy.
  entry: hooks/mypy
  language: script
  minimum_pre_commit_version: 2.9.0
  name: mypy
  types_or: [python, pyi]
- id: symbolic-links
  description: Prevent committing symbolic links
  entry: hooks/symbolic_links.sh
  language: script
  name: symbolic-links
  stages: [commit]
- id: xenon
  description: Run xenon complexity checks.
  entry: hooks/xenon
  language: script
  minimum_pre_commit_version: 2.9.0
  name: xenon
  types_or: [python, pyi]
- id: yapf
  description: Run yapf.
  entry: hooks/yapf
  language: script
  minimum_pre_commit_version: 2.9.0
  name: yapf
  types_or: [python, pyi]
