# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-added-large-files
  - id: check-shebang-scripts-are-executable
  - id: check-json
  - id: check-yaml
  - id: double-quote-string-fixer
  - id: end-of-file-fixer
  - id: no-commit-to-branch
    args: [--branch, master]
  - id: trailing-whitespace
- repo: local
  hooks:
  - id: clang-format-hook
    entry: hooks/clang_format.sh
    language: script
    name: clang-format-hook
    types: [c++]
  - id: dev-marker-hook
    entry: dev_marker_hook
    language: python
    name: dev-marker-hook
  - id: isort-hook
    entry: isort_hook
    language: python
    minimum_pre_commit_version: 2.9.0
    name: isort-hook
    types_or: [python, pyi]
  - id: mypy-hook
    entry: mypy_hook
    language: python
    minimum_pre_commit_version: 2.9.0
    name: mypy-hook
    types_or: [python, pyi]
  - id: pylint-hook
    entry: hooks/pylint.sh
    language: script
    minimum_pre_commit_version: 2.9.0
    name: pylint-hook
    types_or: [python, pyi]
    args: [--fail-under, "8"]
  - id: symbolic-links-hook
    entry: hooks/symbolic_links.sh
    language: script
    name: symbolic-links-hook
    types: [symlink]
  - id: xenon-hook
    entry: xenon_hook
    language: python
    minimum_pre_commit_version: 2.9.0
    name: xenon-hook
    types_or: [python, pyi]
  - id: yapf-hook
    entry: hooks/yapf.sh
    language: script
    minimum_pre_commit_version: 2.9.0
    name: yapf-hook
    types_or: [python, pyi]
