- id: clang-format-hook
  description: Execute clang-format check.
  entry: clang_format_hook
  language: python
  name: clang-format-hook
  stages: [ commit ]
  types: [ c++ ]
- id: dev-marker-hook
  stages: [ commit ]
  description: Prevent committing "dev markers".
  entry: dev_marker_hook
  language: python
  name: dev-marker-hook
- id: isort-hook
  description: Sort Python imports
  entry: isort_hook
  language: python
  minimum_pre_commit_version: 2.9.0
  name: isort-hook
  types_or: [ python, pyi ]
- id: line-endings-hook
  description: Check files are committed with LF endings.
  entry: line_endings_hook
  language: python
  name: line-endings-hook
- id: mypy-hook
  description: Run mypy.
  entry: mypy_hook
  language: python
  minimum_pre_commit_version: 2.9.0
  name: mypy-hook
  types_or: [ python, pyi ]
- id: pylint-hook
  entry: pylint_hook
  language: python
  minimum_pre_commit_version: 2.9.0
  name: pylint-hook
  types_or: [ python, pyi ]
- id: symbolic-links-hook
  stages: [ commit ]
  description: Prevent committing symbolic links
  entry: personal_pre_commit_hooks/hooks/symbolic_links.sh
  language: script
  name: symbolic-links-hook
  types: [ symlink ]
- id: xenon-hook
  description: Run xenon complexity checks.
  entry: xenon_hook
  language: python
  minimum_pre_commit_version: 2.9.0
  name: xenon-hook
  types_or: [ python, pyi ]
- id: yapf-hook
  description: Run yapf.
  entry: yapf_hook
  language: python
  minimum_pre_commit_version: 2.9.0
  name: yapf-hook
  types_or: [ python, pyi ]
