name: BuildChecks

on:
  pull_request:
    branches:
      - master
    types:
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: actions/setup-python@v4.5.0
        with:
          python-version: '3.8'
      - name: PrepareEnv
        run: python -mpip install pipenv
      - name: Install Dependencies
        run: pipenv sync --dev
      - name: Generate Requirements
        run: python generate_requirements.py --output-file pipfile_requirements_test.txt
      - name: Check Requirements Are Up To Data
        run: diff pipfile_requirements.txt pipfile_requirements.txt
      - name: Check Tag Is New
        run: "[[ -z $(git tag -l | grep -E ^$(cat VERSION)$) ]]"
