name: TagRelease

on:
  push:
    branches:
      - master
      - dev/*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Version
        id: version
        uses: juliangruber/read-file-action@v1
        with:
          path: ./VERSION
