name: TagRelease

on:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Read Version
        id: version
        uses: juliangruber/read-file-action@v1.1.6
        with:
          path: ./VERSION
      - name: Create/Update tag
        uses: rickstaa/action-create-tag@v1.6.1
        with:
          tag: "${{ steps.version.outputs.content }}"
